apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-app
  namespace: weather
  labels:
    app: weather-app
spec:
  selector:
    matchLabels:
      app: weather-app
  endpoints:
  - port: http
    path: /
    interval: 30s
    scrapeTimeout: 10s
