replicaCount: 1

ingress:
  className: "nginx"
  hosts:
    - host: weather.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false

monitoring:
  enabled: false
  serviceMonitor:
    enabled: false

