replicaCount: 3

ingress:
  className: "webapp-routing"
  annotations:
    kubernetes.io/ingress.class: webapp-routing
  hosts:
    - host: weather.azure.internal
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

monitoring:
  serviceMonitor:
    enabled: true
