apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weather-platform.fullname" . }}-secrets
  labels:
    {{- include "weather-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  groq-api-key: {{ .Values.secrets.groqApiKey | quote }}
